backend:
  name: git-gateway
  branch: master
media_folder: "assets/images"
collections:
  - name: "blog"
    label: "Blog"
    slug: "{{slug}}"
    folder: "_blog/"
    editor:
      preview: false
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "foblogs",
        }
      - { label: "Collection", name: "tags", widget: "hidden", default: "blog" }
      - { label: "Tag", name: "bookmark", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
