backend:
  name: git-gateway
  branch: master

media_folder: "assets/images"

collections: 
  - name: "myRealblogs"
    label: "first blog"
    folder: "_blog"
    create: true
    slug: "{{slug}}"
    fields: 
    - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "foblogs" }
      - { label: "Collection", name: "tags", widget: "hidden", default: "blog" }
      - { label: "Summary", name: "summary", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime", required: true }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }